### ISSUE TITLE
Error while running call_spread.ipynb

### ISSUE THREAD

**Issue by guarin1949** [rgaveiga/optionlab#3] opened 2024-02-23 22:36 UTC
Somehow the call_spread.ipynb generates this error when executed in Jupyter notebook:
![image](https://github.com/rgaveiga/optionlab/assets/33678711/ab4d0a3d-b3d8-4172-ac7e-0667f72c0e8a)
All 'relevant' libraries have been installed: optionlab, matplotlib, pandas, numpy, scipy...

**Comment by rgaveiga** [comment] 2024-02-24 14:17
This is weird. Have you tried to open Python in a terminal and import pi from scipy? Here it works perfectly, as you can see below. Maybe the problem is the scipy version, you can try to update it to the latest one (1.11).
![image](https://github.com/rgaveiga/optionlab/assets/88116667/716118fd-f261-41ee-8efc-277b8f30ae21)

**Comment by rgaveiga** [comment] 2024-02-28 10:54
It seems that Scipy's developers removed pi from it. I will import directly from math. Thank you for point out this issue.

**Comment by jagernicolas** [comment] 2024-02-28 11:29
you can close the issue then

**Comment by marc-at-brightnight** [comment] 2024-03-10 15:15
This is fixed as part of https://github.com/rgaveiga/optionlab/pull/5

**Closed** 2024-03-10 18:49 UTC
